const constants = {
  GET_ACTOR: "GET_ACTOR",
  GET_ACTOR_SUCCESS: "GET_ACTOR_SUCCESS",
  GET_ACTOR_FAIL: "GET_ACTOR_FAIL",
  GET_ACTOR_LIST: "GET_ACTOR_LIST",
  GET_ACTOR_LIST_SUCCESS: "GET_ACTOR_LIST_SUCCESS",
  GET_ACTOR_LIST_FAIL: "GET_ACTOR_LIST_FAIL",
  CRAWL_ACTOR_LIST: "CRAWL_ACTOR_LIST",
  CRAWL_ACTOR_LIST_SUCCESS: "CRAWL_ACTOR_LIST_SUCCESS",
  CRAWL_ACTOR_LIST_FAIL: "CRAWL_ACTOR_LIST_FAIL",
  CRAWL_ACTOR_DETAILS: "CRAWL_ACTOR_DETAILS",
  CRAWL_ACTOR_DETAILS_SUCCESS: "CRAWL_ACTOR_DETAILS_SUCCESS",
  CRAWL_ACTOR_DETAILS_FAIL: "CRAWL_ACTOR_DETAILS_FAIL",
}
export default constants;
