const constants = {
  GET_ACTOR: "GET_ACTOR",
  GET_ACTOR_SUCCESS: "GET_ACTOR_SUCCESS",
  GET_ACTOR_FAIL: "GET_ACTOR_FAIL",
  GET_ACTOR_LIST: "GET_ACTOR_LIST",
  GET_ACTOR_LIST_SUCCESS: "GET_ACTOR_LIST_SUCCESS",
  GET_ACTOR_LIST_FAIL: "GET_ACTOR_LIST_FAIL",
}
export default constants;
